### ISSUE TITLE
Are you aware of the Digraphs package?

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/BlissInterface#1]
Just wanted to mention that the Digraphs package for GAP already contains an interface to Bliss and has done since 2014.

**Comment by james-d-mitchell** [comment]
Ok I can answer my own question, you are aware of Digraphs and some of the source code of BlissInterface is based on/copied from the Digraphs source code. This is fine and all but any chance you could indicate this prominently in the README file? A condition of the GPL license under which the Digraphs code is released is that “The work must carry prominent notices stating that you modified it, and giving a relevant date.“ It’d be great if you could please include this info in the README or somewhere else in the documentation.

**Comment by nagygp** [comment]
Dear @james-d-mitchell , of course I used Digraphs for scientific computation a lot and as you noticed I also used it when writing this package. With my package my intention was to provide a basic interface to bliss, which is very stable and runs very reliably under Windows as well. (The last stable version 0.73 of bliss is from 2015.) In the future, I want to use BlissInterface to compute automorphisms and canonical labellings of combinatorial structures like unitals, Steiner systems and k-nets. Digraphs has a lot of great features which I don't need, and due its active development, it often fails to run on Windows. 

In my last commits to BlissInterface, I made more precise reference to Digraphs in the core file src/BlissInterface.cc. I hope this is now clear enough and acceptable under the GPL license. 

Notice that I also added references to the Digraph and GRAPE packages in the documentation. 

Please have a look to check if the references to Digraphs are now OK.

**Comment by james-d-mitchell** [comment]
Sounds good @nagygp, thanks for the reply and the rationale for the package. Ideally you'd put something about using part of the Digraphs kernel module in the README and/or on the webpage:

https://gap-packages.github.io/BlissInterface/

IMO these are the most prominent places, not so many users will look directly at the source code, maybe not so many more will read the documentation. I don't think this is unfair to ask, when 134 lines out of the 186 lines of code (and comments) in the kernel module comes from Digraphs. 

About the rationale for the package existing in the first place, again in my humble opinion, a better solution would have been for you to report whatever issues you were having with Digraphs so that we have the opportunity to fix them. We welcome contributions to the Digraphs package, and would, in particular, find a contributor using Digraphs on windows very valuable.

**Comment by nagygp** [comment]
Sure, I will rewrite the README file before making the new release and mention Digraphs there as well. 

Concerning reporting an issue, I did this last year  #https://github.com/gap-packages/Digraphs/issues/138 and the fix took 8 months. During this time, my GAP package https://github.com/nagygp/UnitalSZ was unusable under windows. 

In fact, I am an Ubuntu user, and have very little access to windows machines, but many students of mine use windows and it is hard to convince them to wait months for the next GAP release. :-) 

It is also clear that newly, the windows support of GAP packages improves rapidly. Let's hope that this will eliminate such kind of problems.

**Comment by james-d-mitchell** [comment]
Thanks @nagygp. Just want to mention again that the issue you reported wasn’t one that the Digraphs authors created or could fix, bugs in Digraphs are usually fixed promptly, and we will be happy to receive more in the future.
