### ISSUE TITLE
Integration tests for this package

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/BlissInterface#5]
Since this package provides a standard test, I suggest to add it to the two tests that we offer to GAP package authors to test _development_ versions of their packages for compatibility with GAP stable and master branches:
- https://github.com/gap-packages/gap-docker-pkg-tests-master-devel 
- https://github.com/gap-packages/gap-docker-pkg-tests-stable-4.10-devel

The first of these two repositories has a README file with further details. To add your package to the test, please submit a pull request to add a line to the `.travis.yml` file.

**Comment by nagygp** [comment]
Thank you @alex-konovalov ! I need some further help to add BlissInterface to Appveyor. I copied .appveyor.yml file from https://github.com/gap-packages/datastructures but it seems not to do anything. It would be very important for me to know that BlissInterface works well on Windows.

**Comment by olexandr-konovalov** [comment]
You can add one line to those repos anyway - they will run tests every day, even when BlissInterface had no commits, and help to check that changes in GAP do not break BlissInterface. 

Appveyor is an unrelated issue tough, with which I can't help now. Should be a separate issue. Check who added Appveyor setup to datastructures and ask them (maybe @fingolfin ?)

**Comment by nagygp** [comment]
Well, I registered to Appveyor with my Github account, added the project, and both 32-bit and 64-bit integration tests seem to pass. :-) 

I am happy to close the issue.
